### PR TITLE
Update 2legged.md

### PR DESCRIPTION
**Pull request by deepalics0044**
Changes made in 2legged.md for downloading .dwg files

### CODE REVIEW

**Comment by augustogoncalves** [comment]
Please use Autodesk Knowledge base for sample files, [like this for Revit](https://knowledge.autodesk.com/support/revit-products/getting-started/caas/CloudHelp/cloudhelp/2019/ENU/Revit-GetStarted/files/GUID-61EF2F22-3A1F-4317-B925-1E85F138BE88-htm.html). Please search for equivalent articles for AutoCAD & Inventor

**Comment by augustogoncalves** [comment]
thanks, nice to have AutoCAD **mechanical**... is there any "vanilla" AutoCAD too?

**Comment by deepalics0044** [comment]
I found this -[https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html](url)

**Comment by augustogoncalves** [comment]
it's seems a bit old, but should work, please update the PR.

**Comment by augustogoncalves** [comment]
Looking better, seems like mnissing the image: https://github.com/Developer-Autodesk/forge.learning/pull/66/files#diff-db2337ed1f25d50a2f0ffe70bda2a037R93

**Comment by augustogoncalves** [comment]
Merging into [STG](https://learnforge-stg.herokuapp.com), let's see how it looks

**Comment by augustogoncalves** [comment]
image

did some adjusts on the UI, take a look, I think it looks cleaner. 

have you tried the IPTs link? it actually downloads a ZIP, which works on Model Derivative, but this sample doesn't handle it properly (tutorial is just too basic). any suggestions? maybe a different sample link?

**Pull request merged**
