### PR TITLE
Refactoring code snippets

### PR DESCRIPTION
**Pull request by petrbroz**
This is a preparation work for the upcoming localization of https://learnforge.autodesk.io.

Currently, code snippets are embedded directly in Markdown files which means that each code snippet would be duplicated with each localized version of the Markdown file. To avoid that redundancy, this pull request simply moves all the _major_ snippets of code into their own files in the [docs/_snippets](https://github.com/Developer-Autodesk/forge.learning/tree/brozp/refactor-snippets/docs/_snippets) subfolder.

For each commit in this PR I've compared the content generated locally by docsify with https://learnforge.autodesk.io, and haven't found any regressions.

### CODE REVIEW

**Comment by petrbroz** [comment]
Note: docsify also allows embedding of [code fragments](https://docsify.js.org/#/embed-files?id=embedded-code-fragments), so in the future we could consider embedding fragments of code directly from https://github.com/Autodesk-Forge/learn.forge.viewmodels or others.

**Comment by augustogoncalves** [comment]
let's rebase to STG and test it, is that ok?

**Comment by petrbroz** [comment]
Sounds good, thanks!

**Comment by petrbroz** [comment]
@augustogoncalves  I've gone through all the tutorial/language variants on http://learnforge-stg.herokuapp.com (making sure that each code snippet contains the right content), and everything seems ok. I think this update is safe to be merged into master.

**Pull request merged**
